const API = 'https://backboard.railway.com/graphql/v2';
function cfg(){return{token:process.env.RAILWAY_API_TOKEN||process.env.RAILWAY_TOKEN||'',tokenType:(process.env.RAILWAY_TOKEN_TYPE||'ACCOUNT').toUpperCase(),projectId:process.env.RAILWAY_PROJECT_ID||'',environmentId:process.env.RAILWAY_ENVIRONMENT_ID||'',serviceId:process.env.RAILWAY_SERVICE_ID||'',workspaceId:process.env.RAILWAY_WORKSPACE_ID||''};}
async function gql(query,variables={}){const c=cfg();if(!c.token)throw new Error('RAILWAY_API_TOKEN is not set');const headers={'Content-Type':'application/json'};if(c.tokenType==='PROJECT')headers['Project-Access-Token']=c.token;else headers.Authorization=`Bearer ${c.token}`;const res=await fetch(API,{method:'POST',headers,body:JSON.stringify({query,variables})});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(`Railway API HTTP ${res.status}`);if(body.errors?.length)throw new Error(body.errors.map(e=>e.message).join('; '));return body.data;}
async function getContext(){const c=cfg();if(!c.projectId||!c.environmentId||!c.serviceId)return{configured:false,projectId:c.projectId,environmentId:c.environmentId,serviceId:c.serviceId};const data=await gql(`query($pid:String!,$sid:String!,$eid:String!){project(id:$pid){id name environments{edges{node{id name}}} services{edges{node{id name}}}} service(id:$sid){id name} serviceInstance(serviceId:$sid,environmentId:$eid){id serviceId environmentId numReplicas region buildCommand startCommand rootDirectory healthcheckPath source{repo image branch}}}`,{pid:c.projectId,sid:c.serviceId,eid:c.environmentId});return{configured:true,project:data.project,service:data.service,instance:data.serviceInstance};}
async function getVariables(){const c=cfg();return gql(`query($pid:String!,$eid:String!,$sid:String!){variables(projectId:$pid,environmentId:$eid,serviceId:$sid)}`,{pid:c.projectId,eid:c.environmentId,sid:c.serviceId});}
async function setVariables(variables,replace=false){const c=cfg();return gql(`mutation($input:VariableCollectionUpsertInput!){variableCollectionUpsert(input:$input)}`,{input:{projectId:c.projectId,environmentId:c.environmentId,serviceId:c.serviceId,variables,replace,skipDeploys:true}});}
async function updateInstance(input){const c=cfg();return gql(`mutation($sid:String!,$eid:String!,$input:ServiceInstanceUpdateInput!){serviceInstanceUpdate(serviceId:$sid,environmentId:$eid,input:$input)}`,{sid:c.serviceId,eid:c.environmentId,input});}
async function redeploy(){const c=cfg();return gql(`mutation($sid:String!,$eid:String!){serviceInstanceRedeploy(serviceId:$sid,environmentId:$eid)}`,{sid:c.serviceId,eid:c.environmentId});}
async function deployments(limit=12){const c=cfg();const data=await gql(`query($input:JSON,$first:Int){deployments(input:$input,first:$first){edges{node{id status createdAt updatedAt url staticUrl canRedeploy meta}}}}`,{input:{serviceId:c.serviceId,environmentId:c.environmentId},first:limit});return data.deployments.edges.map(x=>x.node);}
async function deploymentLogs(deploymentId,limit=200){return(await gql(`query($id:String!,$limit:Int){deploymentLogs(deploymentId:$id,limit:$limit){timestamp message severity}}`,{id:deploymentId,limit})).deploymentLogs;}
async function metrics(startDate){const c=cfg();return gql(`query($pid:String!,$eid:String!,$sid:String!,$measurements:[String!]!,$start:DateTime!){metrics(projectId:$pid,environmentId:$eid,serviceId:$sid,measurements:$measurements,startDate:$start){measurement values{ts value}}}`,{pid:c.projectId,eid:c.environmentId,sid:c.serviceId,measurements:['cpu','memory','network','disk'],startDate});}
async function billingUsage(){const c=cfg();let workspaceId=c.workspaceId;if(!workspaceId){const ws=await gql(`query{workspaces{id name}}`);workspaceId=ws.workspaces?.[0]?.id||'';}const[usageData,estimateData]=await Promise.all([gql(`query($wid:String,$pid:String){usage(workspaceId:$wid,projectId:$pid){measurement value}}`,{wid:workspaceId||null,pid:c.projectId||null}),gql(`query($wid:String,$pid:String){estimatedUsage(workspaceId:$wid,projectId:$pid){measurement estimatedValue}}`,{wid:workspaceId||null,pid:c.projectId||null})]);return{workspaceId,usage:usageData.usage||[],estimatedUsage:estimateData.estimatedUsage||[]};}
async function domains(){const c=cfg();return gql(`query($pid:String!,$eid:String!,$sid:String!){domains(projectId:$pid,environmentId:$eid,serviceId:$sid) tcpProxies(environmentId:$eid,serviceId:$sid){domain proxyPort applicationPort}}`,{pid:c.projectId,eid:c.environmentId,sid:c.serviceId});}
module.exports={cfg,gql,getContext,getVariables,setVariables,updateInstance,redeploy,deployments,deploymentLogs,metrics,billingUsage,domains};